version: "3.7"
networks:
    e-comerce:

services:
    nginx:
        image: nginx:latest
        working_dir: /var/www
        ports:
            - "80:80"
        volumes:
            - './public:/var/www/public'
            - './storage/app:/var/www/storage/app:cached'
            - './docker/nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf'
        networks:
            - e-comerce
    php-fpm:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
            args:
                - UID=${UID-1000}
                - GID=${GID-1000}
        image: e-comerce-php-fpm
        working_dir: /var/www
        volumes:
            - './:/var/www/'
        networks:
            - e-comerce
    mysql:
        image: mysql:8.1.0
        restart: always
        ports:
            - "3309:3306"
        environment:
            MYSQL_DATABASE: e-comercia
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - './storage/db-data:/var/lib/mysql'
        networks:
            - e-comerce
